ClickEstudios/Accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
      path('account', views.ViewAccounts.as_view(), name='accounts'),
            path('login/', views.Login.as_view(), name='login-accounts'),
                  path('logout/', views.Logouts.as_view(), name='logout'),
                        path('delete-account/<int:pk>/', views.DeleteAccount.as_view(), name='delete-account'),

      path('create-accounts/', views.CreateAccounts.as_view(), name='create-accounts'),
            path('update-accounts/<int:pk>/', views.UpdateAccouns.as_view(), name='update-accounts'),
                  
]

ClickEstudios/ClickEstudios/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404



urlpatterns = [
    path('' , include('Estudios.urls')),
    path('asistente/', include('Asistente.urls')),
    path('admin/', admin.site.urls),
    path('accouns/', include('Accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

handler404 = 'Estudios.views.Status404'
handler404 = 'Estudios.views.error_redirect_view'
handler500 = 'Estudios.views.error_redirect_view'
handler403 = 'Estudios.views.error_redirect_view'
handler400 = 'Estudios.views.error_redirect_view'


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ClickEstudios/Estudios/urls.py
from django.contrib import admin
from django.urls import path
from . import views, ajax_views



app_name = 'estudios'

urlpatterns = [
#  Home
      path('', views.Home.as_view(), name='home'),
            path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
                  path('pos/', views.Pos.as_view(), name='pos'),

# Estudios
      path('estudios/<int:pk>', views.Estudios.as_view(), name='estudios'),
     
# Servcios
      path('service/', views.Service.as_view(), name='service'),
            path('service-create/', views.ServiceCreate.as_view(), name='service-create'),
                  path('service-detail/<int:pk>/', views.ServiceDetail.as_view(), name='service-detail'),
                        path('service-update/<int:pk>/', views.ServiceUpdate.as_view(), name='service-update'),
                  path('service-delete/<int:pk>/', views.ServiceDelete.as_view(), name='service-delete'),
            path('service-client-service/<int:pk>', views.ServiceClientSelect.as_view(), name='service-client-service'),
      path('ofertas-service/<int:pk>', views.OfertasService.as_view(), name='ofertas-service'),
      
# Planes
      path('plan/', views.Plan.as_view(), name='plan'),
            path('plan-create/', views.PlanCreate.as_view(), name='plan-create'),
                  path('plan-detail/<int:pk>/', views.PlanDetail.as_view(), name='plan-detail'),
                        path('plan-update/<int:pk>/', views.PlanUpdate.as_view(), name='plan-update'),
                  path('plan-delete/<int:pk>/', views.PlanDelete.as_view(), name='plan-delete'),

# Ventas
      path('sale/', views.Sale.as_view(), name='sale'),
            path('sale-create/<int:pk>', views.SaleCreate.as_view(), name='sale-create'),
                  path('sale-reserver/<int:pk>', views.SaleReserver.as_view(), name='sale-reserver'),
                        path('sale-update/<int:pk>/', views.SaleUpdate.as_view(), name='sale-update'),
                        path('sale-delete/<int:pk>/', views.SaleDelete.as_view(), name='sale-delete'),
                  path('sale-create-date-choice/<int:pk>/', views.SaleCreateDateChoice.as_view(), name='sale-create-date-choice'),
            path('sale-client-date-choice/<int:pk>/', views.SaleClientDateChoice.as_view(), name='sale-client-date-choice'),
      path('fast-sale', views.FastSale.as_view(), name='fast-sale'),

# Gatos
      path('gastos-create', views.GastosCreate.as_view(), name='gastos-create'),

# Factura 
      path('factura/<int:pk>', views.Factura.as_view(), name='factura'),

# Galeria
      path('gallery/', views.Gallery.as_view(), name='gallery'),
            path('moment-create/', views.MomentCreate.as_view(), name='moment-create'),
                  path('moment-update/<int:pk>/', views.MomentUpdate.as_view(), name='moment-update'),
                        path('moment-delete/<int:pk>/', views.MomentDelete.as_view(), name='moment-delete'),

#  Caja 
      path('box/', views.Box.as_view(), name='box'),
            path('box-create/', views.BoxCreate.as_view(), name='box-create'),

# Aministracion
      path('adminisitracion', views.Admin.as_view(), name='admin'),
            path('empleados/', views.Empleados.as_view(), name='empleados'),
                  path('empleados-create/', views.EmpleadoCreate.as_view(), name='empleados-create'),
                        path('empleados-update/<int:pk>/', views.EmpleadoUpdate.as_view(), name='empleados-update'),
                  path('empleados-delete/<int:pk>/', views.EmpleadoDelete.as_view(), name='empleados-delete'),

# Perfil de usuario
      path('profile-client/<int:pk>/', views.ProfileClient.as_view(), name='profile-client'),

# Yes
      path('yes/', views.Yes.as_view(), name='yes'),

# Login
      path('login/', views.Login.as_view(), name='login'),
            path('logout/', views.Logout.as_view(), name='logout'),

#  Ajax
      path('ajax/verify-date-choice/', ajax_views.VerifyDateChoice, name='verify-date-choice'),
            path('ajax/search/', ajax_views.Search, name='search'),
            path('ajax/search-citas/', ajax_views.SearchCitas, name='search-citas'),
                  path('ajax/get-estudios/', ajax_views.GetEstudios, name='get-estudios'),
            path('ajax/search-move/', ajax_views.SearchMove, name='search-move'),


#  Mhia
      path('mhia/', views.Mhia.as_view(), name='mhia'),

# Configuracion
      path('configuration/', views.Configuration.as_view(), name='configuration'),



#  Facturacion
      path('facturacion/', views.Facturacion.as_view(), name='facturacion'),
            path('list-facturacion/', views.ListFacturacion.as_view(), name='list-facturacion'),
                  path('facturas/', views.Facturas.as_view(), name='facturas'),
                  

# Reportes 

# Contactos
      path('contactos/', views.Contactos.as_view(), name='contactos'),
            path('contacto-create', views.ContactoCreate.as_view(), name='contacto-create'),
                  path('contacto-update<int:pk>', views.ContactoUpdate.as_view(), name='contacto-update'),
            path('contacto-delete<int:pk>', views.ContactoDelete.as_view(), name='contacto-delete'),

      path('citas/', views.Citas.as_view(), name='citas'),
# Correos
      path('correos/', views.Correos.as_view(), name='correos'),
            path('offline/', views.Offline.as_view(), name='offline'),
            
]

ClickEstudios/Estudios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils import timezone


class Profile(models.Model):
      ROLE_CHOICES = [
            ('estandard', 'Estandar'),
            ('administrativo', 'Administrativo'),
            ('administrador', 'Administrador'),
      ]
      user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile', blank=True, null=True)
      phone = models.CharField(max_length=15, blank=True, null=True)
      address = models.TextField(blank=True, null=True)
      img = models.ImageField(upload_to='media/profile', null=True, blank=True)
      role = models.CharField(max_length=30, choices=ROLE_CHOICES, default='estandard')
      estudio = models.ForeignKey('Estudios', on_delete=models.CASCADE, related_name='profile_estudios', null=True, blank=True)

      def __str__(self):
            return f"{self.user.first_name} {self.user.last_name} - {self.get_role_display()}"

class Empleado(models.Model):
      ROLE_CHOICES = [
            ('estandard', 'Estandar'),
            ('administrativo', 'Administrativo'),
            ('administrador', 'Administrador'),
      ]

      user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='empleado', default=1)
      estudio = models.ForeignKey('Estudios', on_delete=models.CASCADE, related_name='empleados', null=True, blank=True)
      name = models.CharField(max_length=100, blank=False, null=False)
      img = models.ImageField(upload_to='media/empleados', null=True, blank=True)
      role = models.CharField(max_length=20, choices=ROLE_CHOICES, default='estandard')
      date_joined = models.DateTimeField(auto_now_add=True)
      is_active = models.BooleanField(default=True)

      class Meta:
            verbose_name = 'empleado'
            verbose_name_plural = 'empleados'

      def __str__(self):
            return f"{self.name} - {self.get_role_display()}"



class Estudios(models.Model):
      user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='admin_estudio')
      empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE, related_name='empleados_estudio', blank=True, null=True)
      name = models.CharField(max_length=100, blank=False, null=False)
      description = models.TextField()
      img = models.ImageField(upload_to='media/estudios', null=True, blank=True, verbose_name='Imagen blanca')
      img_2 = models.ImageField(upload_to='media/estudios', null=True, blank=True, verbose_name='Imagen negra')
      background_img = models.ImageField(upload_to='media/estudios', null=True, blank=True, verbose_name='Imagen de fondo')
      date = models.DateTimeField(auto_now_add=True)

      is_active = models.BooleanField(default=False)

      
      class Meta:
            verbose_name = 'estudio'
            verbose_name_plural = 'estudios'
      
      def __str__(self):
            return self.name


class Service(models.Model):
      name = models.CharField(max_length=100, blank=False, null=False)
      description = models.TextField(blank=True, null=True)
      img = models.ImageField(upload_to='media/servicios', null=True)
      date = models.DateTimeField(auto_now_add=True)

      # Oferta de servicios, seran aplicados a todos los planes de este servicio
      # Si hay una oferta debe de haber un valor mayor a 0 en discount o mount
      
      is_offer = models.BooleanField(default=False)
      discount = models.IntegerField(default=0, blank=True, null=True)
      porcent_discount = models.IntegerField(default=0, blank=True, null=True)
      mount = models.IntegerField(default=0, blank=True, null=True)
      is_active = models.BooleanField(default=True)
      
      class Meta:
            verbose_name = 'servicio'
            verbose_name_plural = 'servicios'
      
      def __str__(self):
            return self.name


class Like(models.Model):
      plan = models.ForeignKey('Plan', on_delete=models.CASCADE, blank=True, null=True, related_name='likes')
      date = models.DateTimeField(auto_now_add=True)
      
      class Meta:
            verbose_name = 'like'
            verbose_name_plural = 'likes'
      
      def __str__(self):
            return self.plan.name

class Plan(models.Model):
      service = models.ForeignKey(Service, on_delete=models.CASCADE, blank=True, null=True, related_name='planes')
      name = models.CharField(max_length=100, blank=False, null=False)
      description = models.TextField( blank=True, null=True)
      price = models.IntegerField(blank=False, null=False)
      img = models.ImageField(upload_to='media/planes', null=True, blank=True)
      img_back = models.ImageField(upload_to='media/planes', null=True, blank=True)
      date = models.DateTimeField(auto_now_add=True)
      is_active = models.BooleanField(default=True)
      
      time = models.TimeField(verbose_name="Hora de inicio", blank=True, null=True, default="08:00")

      # Oferta de planes
      is_offer = models.BooleanField(default=False)
      discount = models.IntegerField(default=0, blank=True, null=True)
      porcent_discount = models.IntegerField(default=0, blank=True, null=True)
      mount = models.IntegerField(default=0, blank=True, null=True)

      class Meta:
            verbose_name = 'plan'
            verbose_name_plural = 'planes'
      
      def __str__(self):
            return self.name





class Caracteristica(models.Model):
      plan = models.ForeignKey(Plan, on_delete=models.CASCADE, blank=True, null=True, related_name='caracteristicas')
      name = models.CharField(max_length=100, blank=False, null=False)
      date = models.DateTimeField(auto_now_add=True)
      
      class Meta:
            verbose_name = 'caracteristica'
            verbose_name_plural = 'caracteristicas'
      
      def __str__(self):
            return self.name


class Moment(models.Model):
      service = models.ForeignKey(Service, on_delete=models.CASCADE, blank=True, null=True, related_name='momentos')
      name = models.CharField(max_length=100, blank=False, null=False)
      img = models.ImageField(upload_to='media/momentos', null=True)
      date = models.DateTimeField(auto_now_add=True)
      
      class Meta:
            verbose_name = 'momento'
            verbose_name_plural = 'momentos'
      
      def __str__(self):
            return self.name



class ImgMoment(models.Model):
      moment = models.ForeignKey(Moment, on_delete=models.CASCADE, blank=True, null=True, related_name='img_moments')
      img = models.ImageField(upload_to='media/imagenes', null=True, blank=True)
      date = models.DateTimeField(auto_now_add=True)
      
      class Meta:
            verbose_name = 'imagen'
            verbose_name_plural = 'imagenes'
      
      def __str__(self):
            return self.img.url
      

      




class Client(models.Model):
      name = models.CharField(max_length=100, blank=True, null=True)
      last_name = models.CharField(max_length=100, blank=True, null=True)
      email = models.EmailField(max_length=100, blank=True, null=True)
      phone = models.CharField(max_length=20, blank=True, null=True)
      date = models.DateTimeField(auto_now_add=True)
      
      class Meta:
            verbose_name = 'cliente'
            verbose_name_plural = 'clientes'
      
      def __str__(self):
            return self.name

# Las sales son las ventas que se realizan en el estudio, son equivalentes a las (citas)
# que se realizan en un estudio de fotografía, en este modelo se almacena la información
# de la venta, el cliente, el plan, los adicionales, el monto, el pago, las fechas de inicio
# y finalización, y el estado de la venta.
class Sale(models.Model):
#  Datos del usuario o cliente
      name_client = models.CharField(max_length=100, blank=True, null=True)
      email_client = models.EmailField(max_length=100, blank=True, null=True)
      phone_client = models.CharField(max_length=20, blank=True, null=True)
      phone_no_formate = models.CharField(max_length=20, blank=True, null=True)  # Teléfono sin formato para whatsapp
      descrition = models.TextField(blank=True, null=True) # Descripción para la venta
      is_cliente = models.BooleanField(default=False) # Si el cliente es nuevo
      client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='client_sale', null=True, blank=True)

      
# Datas de plan escogido
      pk_plan = models.IntegerField(default=0, blank=True, null=True)
      name_plan = models.CharField(max_length=100, blank=True, null=True)
      description_plan = models.TextField(blank=True, null=True)
      price_plan = models.IntegerField(blank=True, null=True)
      img = models.ImageField(upload_to='media/ventas', null=True, blank=True)
      date = models.DateTimeField(default=timezone.now, verbose_name="Fecha de creación", blank=True)
      is_active = models.BooleanField(default=True)

# Estado de la venta
      mount = models.IntegerField(blank=True, null=True, default=0) # Monto que abonado
      debit_mount = models.IntegerField(blank=True, null=True, default=0) # Monto que se debe restante
      is_reserve = models.BooleanField(default=False) # Reserva de la venta
      payment = models.BooleanField(blank=True, null=True) # Pago de la venta

# Procesos de fotografias
      start_proces_date = models.DateField(verbose_name="Fecha de inicio", blank=True, null=True)
      end_proces_date = models.DateField(verbose_name="Fecha final", blank=True, null=True)
      finalize = models.BooleanField(default=False) # Procesos de fotografias finalizado
      saled_date = models.DateField(verbose_name="Fecha de facturación", blank=True, null=True)  # Fecha de facturación

# Cuando se acordo la venta (cita)
      date_choice = models.DateField(verbose_name="Fecha seleccionada", blank=True, null=True) # Fecha de la cita
      HOUR_CHOICES = [(f"{hour:02d}:00", f"{hour:02d}:00") for hour in range(8, 18)]

ClickEstudios/Estudios/templates/service/delete.html
{% extends "base/base.html" %}
{% block content %}
 
      <style>
            .nav .services {
                  color: #ffc107;
                  font-weight: bolder;
                  transform: scale(1.1);
            }
      </style>

      <div class="d-flex justify-content-center align-items-center w-100 h-100">
            <form method="post">
                  {% csrf_token %}
                  {% csrf_token %}
                  <div>
                        <div class="card-img-top " style="
                              {% if object.img %}
                                    background-image: url('{{object.img.url}}');
                              {% endif %}
                              background-size: cover; background-repeat: no-repeat; 
                              filter: brightness(80%);
                              max-width: 30rem;
                              height: 220px; border-radius: 3rem;">
                        </div>
                  </div>
                  <h5 class='text-white'>¿Estás seguro de que deseas eliminar {{object.name}}?</h5>
                  <div class="mt-2">
                        {% if object.planes.all %}
                        <div style='height: 5.7rem;' class='overflow-auto  text-white'>   
                                    <span>
                                          Se eliminarán las siguientes planes asociados al este servicio
                                    </span>
                                     {% for p in  object.planes.all %}
                                        <li class="text-white-50" style="font-size: 14px; list-style:circle;">
                                                {{p.name|truncatechars:32}} 
                                        </li>
                                     {% endfor %}
                                    </div>
                        {% endif %}
                  </div>
              
                  <div class="d-flex justify-content-end">
                        <a href="{% url "estudios:service" %}" class="btn border-0 btn-secondary accordion bg-transparent" style="font-weight: bold;"> Cancelar</a>
                        <button type="submit" class="btn btn-danger p-0 pe-3 ps-3 border-0 rounded-5 ms-1"
                        style="font-size: 14px; font-weight: bold;">
                          Si, estoy seguro
                        </button>
                  </div>
            </form>      
      </div>


{% endblock %}

ClickEstudios/Estudios/templates/service/oferta-service.html
{% extends "base/base.html" %}
{% block content %}
 
<style>
      .nav .services {
            color: #ffc107;
            font-weight: bolder;
            transform: scale(1.1);
      }
      .nav .services svg {
            color: #ffc107 !important;
      }
      .nav .services span {
            color: #ffc107;
      }
      .btn-atras
      {
            display: none;
      }
      input {

            color: #ffffff !important;
      }
      input::placeholder {
            color: #ffffffb8 !important;
      }
      @media (max-width: 600px) {
            .section-service {
            justify-content: center !important;
            }
      }
      .rotate-90
      {
            transform: rotate(180deg);
      }
</style>

<div class="d-flex flex-wrap w-100 vh-100 position-relative">
      <!-- {% if service.is_offer %} -->
            <!-- {% include "service/cp/verific-offer.html" %} -->
      <!-- {% endif %} -->
      <form action="" method="post"  >
            {% csrf_token %}
      <div class="w-100 aplicar-offer d-none">
            {% include "service/cp/aplicar-oferta.html" %}
      </div>
      <div class=" select-plans ">
                  {% include "service/cp/plans.html" %}
            </div>
      </form>
      <div class="w-100 d-flex justify-content-start position-fixed  bottom-0"
            style="margin-bottom: 5rem;">
            <button onclick="Togle()" class="me-0 mt-3 text-black bg-white bg-opacity-25 rounded-circle d-flex justify-content-center flex-wrap align-content-center border-0 change-view "
                  style="width: 2rem; height: 2rem; ">
                  <i class="bi bi-arrow-right-circle-fill"
                         style="font-size: 25px; color: #101010;"></i>
            </button>
            <span onclick="Togle()" class="btn btn-span border-0 bg-transparent mt-3 text-white" style="font-weight: bold;">
                  Administrar ofertas
            </span>
      </div>
</div>
<script>
      let Select_Plans = document.querySelector('.aplicar-offer')
      let Aplicar_Offer = document.querySelector('.select-plans')

      function Togle(){
            Select_Plans.classList.toggle('d-none')
            Aplicar_Offer.classList.toggle('d-none')
            document.querySelector('.change-view').classList.toggle('rotate-90')
            if (Select_Plans.classList.contains('d-none')) {
                  document.querySelector('.btn-span').textContent = 'Administrar ofertas'
            } else {
                  document.querySelector('.btn-span').textContent = 'Aplicar ofertas'
            }
      }

      function OpenOffer(){
            document.querySelector('.div-oferr-active').classList.toggle('d-none')
      }
</script>
{% endblock  %}

ClickEstudios/Estudios/templates/service/service-create.html
{% extends "base/base.html" %}
{% block content %}
      <style>
            #id_img {
                  display: none; 
            }
            .circle {

                        border-radius: 2rem;
                        background-color:rgb(89, 89, 89);
                        display: flex;
                        align-items: center;
                        justify-content: center;
                        cursor: pointer;
                        background-size: cover;
                        background-position: center;
            }
            input, select
            {
                  background-color: #2d2d2d !important;
                  border-radius: 2rem !important; border: none !important;
                  color: white !important; 
                  height: 2.9rem !important; width: 100% !important;
            }
            .btn-atras
            {
                  display: none;
            }
      </style>
      <section class='d-flex flex-wrap w-100 justify-content-center align-content-center '>
            
            <div class="  d-flex  ">
                  <div id="circle" class="circle" style='background-image: url(object.img.url);
                  width: 270px; height: 470px ;
                  ' onclick="document.getElementById('id_img').click()">
                        <span class="blur-50 text-white p-3 rounded-4" style="font-weight: bold;">
                              Cargar img
                        </span>
                  </div>
                    <form action="" method="post" enctype="multipart/form-data">
                        <div class="text-white">
                              <h3 class="m-0">
                                    Creando un nuevo servicio
                              </h3>
                              <p style="font-size: 12px;" class="m-0 text-white-50">
                                    Crea un servicio para tu estudio, con el que podras ofrecer tus servicios a tus clientes
                              </p>

                        </div>
                              {% csrf_token %}
                              <div> 
                                      {{ form.name }}
                              </div>
                              <div>
                                      {{ form.img }}
                              </div>
                              <div class="d-flex justify-content-end">
                                    <a href="{% url "estudios:service" %}">
                                          <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-arrow-left-circle-fill mt-2"  viewBox="0 0 16 16">
                                                <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0m3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5z"/>
                                              </svg>
                                    </a>
                                      <button type="submit" class="btn btn-primary rounded-5 border-0 bg-white bg-opacity-10" style="font-weight: bold; width: 10rem;">
                                                Crear 
                                      </button>
                              </div>
                    </form>
            </div>

      </section>
      <script>
              document.getElementById('id_img').addEventListener('change', function(event) {
                        const file = event.target.files[0];
                        if (file) {
                                const reader = new FileReader();
                                reader.onload = function(e) {
                                          document.getElementById('circle').style.backgroundImage = `url(${e.target.result})`;
                                }
                                reader.readAsDataURL(file);
                        }
              });
      </script>
{% endblock  %}

ClickEstudios/Estudios/templates/service/service-select.html
{% if service_select %}

      <a href="{% url "estudios:service-update" service_select.id %}">
            <div style='width: 320px;'>
                  <div class="" style="
                        {% if service_select.img %}
                              background-image: url('{{service_select.img.url}}');
                        {% endif %}
                        background-size: cover; background-repeat: no-repeat;; width: 320px; height: 220px; border-radius: 2rem;">
                  </div>
                  <h5>{{service_select.name}}</h5>
            </div>
      </a>

{% endif %}

ClickEstudios/Estudios/templates/service/service-update.html
{% extends "base/base.html" %}
{% block content %}
      <style>
            #id_img {
                  display: none; 
            }
            .circle {

                        border-radius: 2rem;
                        background-color:rgb(89, 89, 89);
                        display: flex;
                        align-items: center;
                        justify-content: center;
                        cursor: pointer;
                        background-size: cover;
                        background-position: center;
            }
            input, select
            {
                  background-color: #2d2d2d !important;
                  border-radius: 2rem !important; border: none !important;
                  color: white !important; 
                  height: 2.9rem !important; width: 100% !important;
            }
            .btn-atras
            {
                  display: none;
            }
      </style>
      <section class='d-flex flex-wrap w-100 justify-content-center align-content-center '>
            
            <div class="  d-flex  ">
                  <div id="circle" class="circle" style='background-image: url({{object.img.url}});
                  width: 270px; height: 470px ;
                  ' onclick="document.getElementById('id_img').click()">
                        <span class="blur-50 text-white p-3 rounded-4" style="font-weight: bold;">
                              Cargar img
                        </span>
                  </div>
                    <form action="" method="post" enctype="multipart/form-data">
                        <div class="text-white">
                              <h3 class="m-0">
                                    Actualizando el servicio: {{object.name}}
                              </h3>
                              <p style="font-size: 12px;" class="m-0 text-white-50">
                                    Actualizando servicio para el estudio, con el que ofreces actualmente {{object.planes.all|length}} planes
                              </p>

                        </div>
                              {% csrf_token %}
                              <div> 
                                      {{ form.name }}
                              </div>
                              <div>
                                      {{ form.img }}
                              </div>
                              <div class="d-flex justify-content-end">
                                    <a href="{% url "estudios:service" %}">
                                          <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-arrow-left-circle-fill mt-2"  viewBox="0 0 16 16">
                                                <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0m3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5z"/>
                                              </svg>
                                    </a>
                                      <button type="submit" class="btn btn-primary rounded-5 border-0 bg-white bg-opacity-10" style="font-weight: bold; width: 10rem;">
                                                Actualizar 
                                      </button>
                              </div>
                    </form>
            </div>

      </section>
      <script>
              document.getElementById('id_img').addEventListener('change', function(event) {
                        const file = event.target.files[0];
                        if (file) {
                                const reader = new FileReader();
                                reader.onload = function(e) {
                                          document.getElementById('circle').style.backgroundImage = `url(${e.target.result})`;
                                }
                                reader.readAsDataURL(file);
                        }
              });
      </script>
{% endblock  %}