ClickEstudios/Accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
      path('account', views.ViewAccounts.as_view(), name='accounts'),
            path('login/', views.Login.as_view(), name='login-accounts'),
                  path('logout/', views.Logouts.as_view(), name='logout'),
                        path('delete-account/<int:pk>/', views.DeleteAccount.as_view(), name='delete-account'),

      path('create-accounts/', views.CreateAccounts.as_view(), name='create-accounts'),
            path('update-accounts/<int:pk>/', views.UpdateAccouns.as_view(), name='update-accounts'),
                  
]

ClickEstudios/ClickEstudios/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404



urlpatterns = [
    path('' , include('Estudios.urls')),
    path('asistente/', include('Asistente.urls')),
    path('admin/', admin.site.urls),
    path('accouns/', include('Accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

handler404 = 'Estudios.views.Status404'
handler404 = 'Estudios.views.error_redirect_view'
handler500 = 'Estudios.views.error_redirect_view'
handler403 = 'Estudios.views.error_redirect_view'
handler400 = 'Estudios.views.error_redirect_view'


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ClickEstudios/Estudios/urls.py
from django.contrib import admin
from django.urls import path
from . import views, ajax_views



app_name = 'estudios'

urlpatterns = [
#  Home
      path('', views.Home.as_view(), name='home'),
            path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
                  path('pos/', views.Pos.as_view(), name='pos'),

# Estudios
      path('estudios/<int:pk>', views.Estudios.as_view(), name='estudios'),
     
# Servcios
      path('service/', views.Service.as_view(), name='service'),
            path('service-create/', views.ServiceCreate.as_view(), name='service-create'),
                  path('service-detail/<int:pk>/', views.ServiceDetail.as_view(), name='service-detail'),
                        path('service-update/<int:pk>/', views.ServiceUpdate.as_view(), name='service-update'),
                  path('service-delete/<int:pk>/', views.ServiceDelete.as_view(), name='service-delete'),
            path('service-client-service/<int:pk>', views.ServiceClientSelect.as_view(), name='service-client-service'),
      path('ofertas-service/<int:pk>', views.OfertasService.as_view(), name='ofertas-service'),
      
# Planes
      path('plan/', views.Plan.as_view(), name='plan'),
            path('plan-create/', views.PlanCreate.as_view(), name='plan-create'),
                  path('plan-detail/<int:pk>/', views.PlanDetail.as_view(), name='plan-detail'),
                        path('plan-update/<int:pk>/', views.PlanUpdate.as_view(), name='plan-update'),
                  path('plan-delete/<int:pk>/', views.PlanDelete.as_view(), name='plan-delete'),

# Ventas
      path('sale/', views.Sale.as_view(), name='sale'),
            path('sale-create/<int:pk>', views.SaleCreate.as_view(), name='sale-create'),
                  path('sale-reserver/<int:pk>', views.SaleReserver.as_view(), name='sale-reserver'),
                        path('sale-update/<int:pk>/', views.SaleUpdate.as_view(), name='sale-update'),
                        path('sale-delete/<int:pk>/', views.SaleDelete.as_view(), name='sale-delete'),
                  path('sale-create-date-choice/<int:pk>/', views.SaleCreateDateChoice.as_view(), name='sale-create-date-choice'),
            path('sale-client-date-choice/<int:pk>/', views.SaleClientDateChoice.as_view(), name='sale-client-date-choice'),
      path('fast-sale', views.FastSale.as_view(), name='fast-sale'),

# Gatos
      path('gastos-create', views.GastosCreate.as_view(), name='gastos-create'),

# Factura 
      path('factura/<int:pk>', views.Factura.as_view(), name='factura'),

# Galeria
      path('gallery/', views.Gallery.as_view(), name='gallery'),
            path('moment-create/', views.MomentCreate.as_view(), name='moment-create'),
                  path('moment-update/<int:pk>/', views.MomentUpdate.as_view(), name='moment-update'),
                        path('moment-delete/<int:pk>/', views.MomentDelete.as_view(), name='moment-delete'),

#  Caja 
      path('box/', views.Box.as_view(), name='box'),
            path('box-create/', views.BoxCreate.as_view(), name='box-create'),

# Aministracion
      path('adminisitracion', views.Admin.as_view(), name='admin'),
            path('empleados/', views.Empleados.as_view(), name='empleados'),
                  path('empleados-create/', views.EmpleadoCreate.as_view(), name='empleados-create'),
                        path('empleados-update/<int:pk>/', views.EmpleadoUpdate.as_view(), name='empleados-update'),
                  path('empleados-delete/<int:pk>/', views.EmpleadoDelete.as_view(), name='empleados-delete'),

# Perfil de usuario
      path('profile-client/<int:pk>/', views.ProfileClient.as_view(), name='profile-client'),

# Yes
      path('yes/', views.Yes.as_view(), name='yes'),

# Login
      path('login/', views.Login.as_view(), name='login'),
            path('logout/', views.Logout.as_view(), name='logout'),

#  Ajax
      path('ajax/verify-date-choice/', ajax_views.VerifyDateChoice, name='verify-date-choice'),
            path('ajax/search/', ajax_views.Search, name='search'),
            path('ajax/search-citas/', ajax_views.SearchCitas, name='search-citas'),
                  path('ajax/get-estudios/', ajax_views.GetEstudios, name='get-estudios'),
            path('ajax/search-move/', ajax_views.SearchMove, name='search-move'),


#  Mhia
      path('mhia/', views.Mhia.as_view(), name='mhia'),

# Configuracion
      path('configuration/', views.Configuration.as_view(), name='configuration'),



#  Facturacion
      path('facturacion/', views.Facturacion.as_view(), name='facturacion'),
            path('list-facturacion/', views.ListFacturacion.as_view(), name='list-facturacion'),
                  path('facturas/', views.Facturas.as_view(), name='facturas'),
                  

# Reportes 

# Contactos
      path('contactos/', views.Contactos.as_view(), name='contactos'),
            path('contacto-create', views.ContactoCreate.as_view(), name='contacto-create'),
                  path('contacto-update<int:pk>', views.ContactoUpdate.as_view(), name='contacto-update'),
            path('contacto-delete<int:pk>', views.ContactoDelete.as_view(), name='contacto-delete'),

      path('citas/', views.Citas.as_view(), name='citas'),
# Correos
      path('correos/', views.Correos.as_view(), name='correos'),
            path('offline/', views.Offline.as_view(), name='offline'),
            
]

ClickEstudios/Accounts/models.py
from django.db import models

ClickEstudios/Accounts/views.py
from django.contrib import messages
from django.views.generic import TemplateView, CreateView, UpdateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.views.generic import DeleteView
from django.urls import reverse_lazy


class ViewAccounts(TemplateView):
      template_name = "accounts/accounts/view-accounts.html"


class Login(LoginView):
    template_name = "accounts/login-accounts.html"
    redirect_authenticated_user = True

    def get_success_url(self):
        return self.get_redirect_url() or "/"

    def form_invalid(self, form):
        messages.error(self.request, "Usuario o contraseña incorrectos")
        return super().form_invalid(form)

class Logouts(TemplateView):
      template_name = "accounts/logout-accounts.html"

      def post(self, request, *args, **kwargs):
            logout(request)
            return redirect("/")



class CreateAccounts(CreateView):
    model = User
    form_class = User
    template_name = "accounts/accounts/create-accounts.html"

    def get_success_url(self):
        return redirect("/")



class UpdateAccouns(TemplateView):
    template_name = "accounts/accounts/update-accounts.html"

    def get_success_url(self):
        return self.request.path



class DeleteAccount(DeleteView):
    model = User
    template_name = "accounts/delete-accounts.html"
    success_url = reverse_lazy("home")
   

    def get_object(self, queryset=None):
        return self.request.user
    

    
    

ClickEstudios/Accounts/templates/accounts/delete-accounts.html
{% extends "base/base.html" %}
{% block content %}

      <section>
            <h6>
                  Estas seguro de seas eliminar tu cuenta?
            </h6>
            <p>
                  Esta acción no se puede deshacer y eliminará todos tus datos asociados a la cuenta, incluyendo pedidos, historial y preferencias. Si estás seguro de continuar, haz clic en el botón de abajo para proceder con la eliminación de tu cuenta.
            </p>
            <form action="" method="post">
                  <input type="hidden" name="delelte-account" value="true">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-danger">
                        Eliminar cuenta
                  </button>
                  <a href="{% url 'accounts:accounts' %}" class="btn btn-secondary">
                        Cancelar
                  </a>
            </form>
      </section>

{% endblock %}

ClickEstudios/Accounts/templates/accounts/login-accounts.html
<link rel="stylesheet" href="https://cdn-uicons.flaticon.com/uicons-solid-rounded/css/uicons-solid-rounded.css">
      <style>
            .logout {
                  background-image: url('https://img.freepik.com/free-vector/blurred-background-with-light-colors_1034-245.jpg?semt=ais_hybrid&w=740');
                  background-position: center; background-repeat: no-repeat;
                  background-size: cover;
            }
      </style>
      <section class="logout d-flex  flex-wrap justify-content-center  align-content-center  vh-100 w-100">
            <div style=" background: linear-gradient(to bottom, transparent, #101010), linear-gradient(to top, transparent, #101010);"
                      class="vh-100 w-100 d-flex position-relative align-content-end flex-wrap p-3 ">
                      {% if messages %}
                      <div class="d-flex position-absolute justify-content-center top-0 start-0 w-100" >
                            {% for message in messages %}
                            <div class="alert alert-danger bg-black bg-opacity-25  mt-2 ps-5 pe-5 rounded-5" style="color: #fdfdfdb6;
                                font-size: 0.9rem;
                                border: 0px solid #fdfdfd54;
                                margin-bottom: 0.5rem;
                                max-width: max-content;">
                                      {{ message }}
                                {% endfor %}
                          </div>
                      </div>
                      <script>
                        setTimeout(() => {
                              const alerts = document.querySelectorAll('.alert');
                              alerts.forEach(alert => {
                                    alert.style.display = 'none';
                              });
                        }, 5000);
                      </script>
                    {% endif %}
                      <form method="post" action="" style="
                      background: #19191900; padding: 0.2rem;
                       border-radius: 1.5rem;
                        width: 100%; max-width: 500px; font-family: 'Segoe UI', sans-serif;">
                        {% csrf_token %}
                        <!-- <h2 style="margin-bottom: 0.3rem; font-size: 1.5rem; color: #fff; text-align: start;">Iniciar sesión</h2> -->
                          <p class="text-white-50" style="font-size: 14px;">
                              Accede a tu cuenta para gestionar tus pedidos, revisar tu perfil y utilizar todas las funcionalidades disponibles
                          </p>
                        <div style="margin-bottom: 0.3rem;">
                          <input type="text" id="username" name="username" placeholder="Usuario o correo" required
                            style="width: 100%; padding: 1rem; background-color: #101010a2; color: #eee; border: 1px solid #202020; border-radius: 2rem; font-size: 1rem;">
                        </div>
                        <div style="margin-bottom: 1.5rem;">
                          <input type="password" id="password" name="password" placeholder="Contraseña" required
                            style="width: 100%; padding: 1rem; background-color: #101010a2; color: #eee; border: 1px solid #202020; border-radius:2rem; font-size: 1rem;">
                        </div>
                        <div class="w-100 d-flex justify-content-center">
                              <button type="submit" class="bold"
                              style="width: 200px; padding: 0.75rem; background-color: #4d4d4d56; color: white; border: none; border-radius: 2rem; font-size: 1rem; cursor: pointer;">
                              Iniciar sesión
                            </button>
                        </div>
                          <a class="w-100 text-center btn mt-2 p-2 text-white-50 bold d-flex justify-content-center text-decoration-none   " 
                              href="{% url 'estudios:home' %}">
                                No, volver atrás
                          </a>
                      </form>
            </div>
      </section>
      <script>
            document.getElementById('username').addEventListener('input', function (event) {
                        const input = event.target;
                        const regex = /^[a-z0-9@.]*$/; // Allow only lowercase letters, numbers, '@', and '.'
                        if (!regex.test(input.value)) {
                                      input.value = input.value.replace(/[^a-z0-9@.]/g, ''); // Remove invalid characters
                        }
            });
      </script>

ClickEstudios/Accounts/templates/accounts/logout-accounts.html
{% extends "base/base.html" %}
{% block content %}
<link rel="stylesheet" href="https://cdn-uicons.flaticon.com/uicons-solid-rounded/css/uicons-solid-rounded.css">
      <section class="logout d-flex text-white  flex-wrap justify-content-center  align-content-center  vh-100 w-100">

                      <h5 class="w-100 text-center">
                            ¿Deseas cerrar session?
                      </h5>
                    <p>  Al cerrar tu sesión, se finaliza el acceso a tu cuenta en este navegador</p>
                 
                  <div class="d-flex w-100 justify-content-center">
                        <a class=" text-center btn p-2 me-3 border-0 bold d-flex justify-content-center text-decoration-none   " 
                        href="{% url 'accounts:accounts' %}" style="width: max-content;">
      
                               No, volver atrás
                        </a>
      
                        <form method="POST" class=" ">
                              {% csrf_token %}
                              <button type="submit" class="btn bold  border-danger text-danger  rounded-5 p-2 ps-4 d-flex flex-wrap align-content-center  pe-4"
                              style="background-color: var(--bg-1);
                              /* border: 1px solid #b8b8b8; */
                              /* background-color: #ff00007a; */
                              width: max-content;">
                              Cerrar sesión</button>
                        </form>
      
                  </div>
      </section>
{% endblock  %}