ClickEstudios/Accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
      path('account', views.ViewAccounts.as_view(), name='accounts'),
            path('login/', views.Login.as_view(), name='login-accounts'),
                  path('logout/', views.Logouts.as_view(), name='logout'),
                        path('delete-account/<int:pk>/', views.DeleteAccount.as_view(), name='delete-account'),

      path('create-accounts/', views.CreateAccounts.as_view(), name='create-accounts'),
            path('update-accounts/<int:pk>/', views.UpdateAccouns.as_view(), name='update-accounts'),
                  
]

ClickEstudios/ClickEstudios/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404



urlpatterns = [
    path('' , include('Estudios.urls')),
    path('asistente/', include('Asistente.urls')),
    path('admin/', admin.site.urls),
    path('accouns/', include('Accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

handler404 = 'Estudios.views.Status404'
handler404 = 'Estudios.views.error_redirect_view'
handler500 = 'Estudios.views.error_redirect_view'
handler403 = 'Estudios.views.error_redirect_view'
handler400 = 'Estudios.views.error_redirect_view'


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ClickEstudios/Accounts/models.py
from django.db import models

ClickEstudios/Accounts/views.py
from django.contrib import messages
from django.views.generic import TemplateView, CreateView, UpdateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.views.generic import DeleteView
from django.urls import reverse_lazy


class ViewAccounts(TemplateView):
      template_name = "accounts/accounts/view-accounts.html"


class Login(LoginView):
    template_name = "accounts/login-accounts.html"
    redirect_authenticated_user = True

    def get_success_url(self):
        return self.get_redirect_url() or "/"

    def form_invalid(self, form):
        messages.error(self.request, "Usuario o contraseña incorrectos")
        return super().form_invalid(form)

class Logouts(TemplateView):
      template_name = "accounts/logout-accounts.html"

      def post(self, request, *args, **kwargs):
            logout(request)
            return redirect("/")



class CreateAccounts(CreateView):
    model = User
    form_class = User
    template_name = "accounts/accounts/create-accounts.html"

    def get_success_url(self):
        return redirect("/")



class UpdateAccouns(TemplateView):
    template_name = "accounts/accounts/update-accounts.html"

    def get_success_url(self):
        return self.request.path



class DeleteAccount(DeleteView):
    model = User
    template_name = "accounts/delete-accounts.html"
    success_url = reverse_lazy("home")
   

    def get_object(self, queryset=None):
        return self.request.user
    

    
    

ClickEstudios/Accounts/templates/accounts/cp/links.html
{% load socialaccount %}
<style>
      .accounts-section {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(330px, 1fr));
        gap: 10px;
      
      }
    
      .accounts-section h2 {
        font-size: 2rem;
        margin-bottom: 0.5rem;
        color: #333;
      }
    
      .accounts-section p {
            font-size: 1rem;
            color: #666;
      }
    
      .account-link {
            height: 170px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            text-decoration: none;
            padding: 0.8rem;
            border-radius: 2.9rem;
            transition: 0.3s ;
            background-color: rgba(25, 25, 25, 0.552);
            border: 1px solid #34343427;
            color: #858585;
      }

      .account-link:hover {
            transform: scale(1.02);
      }
      
      .account-link div {
            display: flex;  align-content: center;
      }
      .account-link div span {
            display: flex;
            flex-wrap: wrap;
            align-content: center;
      }
      .account-link h3 {
            width: 100%;
            margin: 0 !important;
            font-size: 1rem;
            font-weight: bold;
            color: inherit;

      }
    
      .accounts-section i {
            min-width: 70px; min-height: 70px;
            max-width: 70px; max-height: 70px;
            border-radius: 50%;
            font-size: 25px;
            margin: 0;
            margin-right: 1rem;
            margin-left: 0.6rem;
            display: flex; align-content: center; flex-wrap: wrap;
            justify-content: center;
            background-color: var(--bg-0);
      }

      .account-link p {
        margin: 0;
        font-size: 0.9rem;
        color: inherit;
      }
    
      .logout { 
            background-color: rgba(255, 0, 0, 0.094); 
      }
      .logout h3 {
           color: rgba(255, 255, 255, 0.751);
      }
      .logout p {
            color: rgba(255, 255, 255, 0.515);
      }
 
</style>
<div class="accounts-section p-3 mt-2 mb-5 pb-5 w-100">
      <a href="https://myaccount.google.com/data-and-privacy" class="account-link register">
            <div>
                  <i class="fi fi-brands-google"></i>
                  <span>
                  <h3>
                        Cuenta de google      
                  </h3>
                  <p>Editar datos de mi google</p></span>
            </div>
      </a>
      
      <a href="{% url 'accounts:delete-account' request.user.id %}" class="account-link d-none profile">
            <div>
                  <i class="fi fi-sr-heart-crack"></i>
                  <span>
                        <h3>
                              Eliminar cuenta
                        </h3>
                        <p>
                              Eliminacion total de tu cuenta existente en el sistema
                        </p>
                  </span>
            </div>
      </a>
      
      <a href="#" class="account-link login d-none">
            <div>
                  <i class="fi fi-sr-list"></i>
                  <span>
                        <h3>
                              Lista de cuentas</h3>
                        <p>Consulta todas las cuentas registradas</p>
                  </span>
            </div>
      </a>
      
      <a href="#" class="account-link reset d-none">
            <div>
                  <i class="fi fi-sr-time-twenty-four"></i>
                  <span>
                        <h3>
                              Historial de sesiones
                        </h3>
                        <p>
                              Ver desde dónde y cuándo se ha logueado un usuario</p>
                  </span>
            </div>
      </a>
      <a href="{% url 'accounts:update-accounts' request.user.id %}"   class="account-link reset">
            <div>
                  <i class="fi fi-sr-info"></i>
                  <span>
                        <h3>
                              información de cuenta
                        </h3>
                        <p>
                              Consulta y actualiza la información de tu cuenta personal
                        </p>
                  </span>
            </div>
      </a>
      <a class="account-link reset">
            <div>
                  <i class="fi fi-sr-building"></i>
                  <span>
                        <h3>
                              Administrador empresa
                        </h3>
                        <p>
                              Consulta y actualiza la información de la empresa
                        </p>
                  </span>
            </div>
      </a>
      <a href="#" class="account-link reset d-none">
            <div>
                  <i class="fi fi-sr-download"></i>
                  <span>
                        <h3>
                              Exportar datos
                        </h3>
                        <p>
                              Para permitir al usuario exportar su información o la de su cuenta
                        </p>
                  </span>
            </div>
      </a>
      <a href=" {% url 'accounts:logout' %} " class="account-link reset">
            <div>
                  <i class="fi fi-sr-user-logout"></i>
                  <span>
                        <h3>
                              Cerrar session
                        </h3>
                        <p>
                                Finaliza tu sesión de manera segura
                        </p>
                  </span>
            </div>
      </a>
</div>